image: haskell:8.6.3

build:
  before_script:
    - apt-get update && apt-get install -y libpcre3-dev
    - mkdir -p .stack-root .stack-work
  script:
    >- 
      stack
      --no-terminal
      --stack-root ${CI_PROJECT_DIR}/.stack-root
      --work-dir .stack-work
      test --coverage
  cache:
    paths:
      - .stack-root
      - .stack-work
  artifacts:
    paths:
      - .stack-work/install/x86_64-linux/lts-12.11/8.4.3/hpc

pages:
  stage: deploy
  dependencies:
    - build
  script:
    mv .stack-work/install/x86_64-linux/lts-12.11/8.4.3/hpc/ public/
  artifacts:
    paths:
      - public
    expire_in: 10 days
  only:
    - master
