image: haskell:8.6.3

build:
  before_script:
    - apt-get update && apt-get install -y libpcre3-dev
    - mkdir -p .stack-root .stack-work
  script:
    >- 
      stack
      --no-terminal
      --stack-root ${CI_PROJECT_DIR}/.stack-root
      --work-dir .stack-work
      test --coverage
  after_script:
    - mkdir -p coverage bin
    - mv $(stack path --local-hpc-root) coverage
    - mv $(stack path --local-install-root)/bin bin
  cache:
    paths:
      - .stack-root
      - .stack-work
  artifacts:
    paths:
      - coverage
      - bin

pages:
  stage: deploy
  dependencies:
    - build
  script:
    mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 10 days
  only:
    - master
